# Generated by Django 5.2.4 on 2025-07-26 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('position', models.TextField(null=True)),
                ('dateofjoining', models.DateField(null=True)),
                ('profilePicture', models.ImageField(null=True, upload_to='static/img/DP')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.departmentmodel')),
                ('employerUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
