# Generated by Django 5.2.3 on 2025-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/img')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('adress', models.TextField(max_length=100)),
                ('summary', models.TextField(max_length=100)),
                ('Degree', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=100)),
                ('yearOfGraduation', models.IntegerField()),
                ('companyName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=30)),
                ('yearOfExperience', models.CharField(max_length=10)),
                ('skills', models.TextField(max_length=100)),
                ('hobbies', models.TextField(max_length=100)),
                ('achievements', models.TextField(max_length=100)),
            ],
        ),
    ]
