# Generated by Django 5.2.1 on 2025-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
            ],
        ),
    ]
