# Generated by Django 5.2.3 on 2025-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=400)),
                ('instructions', models.TextField(max_length=400)),
                ('recipeImage', models.ImageField(upload_to='static/recipe/')),
                ('creator', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
