# Generated by Django 5.2.4 on 2025-07-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_portfoliomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='title',
            new_name='fullName',
        ),
    ]
