# Generated by Django 5.2.1 on 2025-05-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Number', models.IntegerField()),
                ('Course_Credit', models.IntegerField()),
                ('Course_Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Department_Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Designation', models.CharField(max_length=150)),
            ],
        ),
    ]
